# Generated by Django 3.2.16 on 2023-02-14 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230209_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='email',
            new_name='newsletter_email',
        ),
    ]
