# Generated by Django 3.2.16 on 2023-02-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_email_newsletter_newsletter_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='test.test.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default='tester', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(default='fake message'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='newsletter_email',
            field=models.EmailField(default='test@test.com', max_length=254),
            preserve_default=False,
        ),
    ]
